name = "aeroc-admin-dashboard"
main = "worker.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "aeroc-admin-db"
database_id = "0dc8dadf-f3d7-4475-a7e2-362d7dd91209"

[[r2_buckets]]
binding = "R2"
bucket_name = "aeroc-admin-files"
